const archiveData = [
  {
    id: "single_かくれんぼ",
    type: "single",
    title: "かくれんぼ",
    date: "2019.12.1",
    media: {
      youtube: "https://youtu.be/7W-6qJnza5w?si=5tjiEsXR9evEaGsT",
    },
  },
  {
    id: "single_かごめ",
    type: "single",
    title: "かごめ",
    date: "2020.2.28",
    media: {
      youtube: "https://youtu.be/PR52T_fpWO4?si=0CUKIYJCw1PcKc3R",
    },
  },
  {
    id: "single_ピーターパン",
    type: "single",
    title: "ピーターパン",
    date: "2020.8.9",
    media: {
      youtube: "https://youtu.be/9qfPF4fpiHE?si=t4FnaT97_gDdXKYU",
    },
  },
  {
    id: "single_ドライフラワー",
    type: "single",
    title: "ドライフラワー",
    date: "2020.10.25",
    media: {
      youtube: "https://youtu.be/kzZ6KXDM1RI?si=aVIqMhmXWFGL5f5b",
    },
  },
  {
    id: "single_インフィニティ",
    type: "single",
    title: "インフィニティ",
    date: "2021.1.23",
    media: {
      youtube:
        "https://music.youtube.com/watch?v=qWfnM-8yyBc&si=XtRY7CvD6_ACL0Qa",
    },
  },
  {
    id: "single_桜晴",
    type: "single",
    title: "桜晴",
    date: "2021.2.19",
    media: {
      youtube:
        "https://music.youtube.com/watch?v=EYcMOogE_xA&si=ND5oYfCzpCu_p-2S",
    },
  },
  {
    id: "single_飛行船",
    type: "single",
    title: "飛行船",
    date: "2021.4.17",
    media: {
      youtube: "https://youtu.be/38xNKy9e-0A?si=omo4dlwKloISMXTw",
    },
  },
  {
    id: "single_シャッター",
    type: "single",
    title: "シャッター",
    date: "2021.7.7",
    media: {
      youtube: "https://youtu.be/EZ5RGA2UULE?si=kVvjRb5-OutME4Ml",
    },
  },
  {
    id: "single_夏音",
    type: "single",
    title: "夏音",
    date: "2021.9.19",
    media: {
      youtube:
        "https://music.youtube.com/watch?v=FVGRHm_NWu0&si=i7MG_IKIB0uM3Kwc",
    },
  },
  {
    id: "single_ベテルギウス",
    type: "single",
    title: "ベテルギウス",
    date: "2021.11.4",
    media: {
      youtube: "https://youtu.be/cbqvxDTLMps?si=zJoRW36-8yLqcS_W",
    },
  },
  {
    id: "single_うぉ",
    type: "single",
    title: "うぉ",
    date: "2022.5.13",
    media: {
      youtube: "https://youtu.be/-0OZ7yueQzA?si=oVs-purAjS1skODK",
    },
  },
  {
    id: "single_タイムマシン ",
    type: "single",
    title: "タイムマシン ",
    date: "2022.7.12",
    media: {
      youtube:
        "https://music.youtube.com/watch?v=bmcVVOwkhE4&si=niI6c6tFHqLQmjqM",
    },
  },
  {
    id: "single_おにごっこ",
    type: "single",
    title: "おにごっこ",
    date: "2022.9.12",
    media: {
      youtube: "https://youtu.be/m3VnVRHOMZM?si=MgfDzSlvT6fyVySw",
    },
  },
  {
    id: "single_クリスマスイブ",
    type: "single",
    title: "クリスマスイブ",
    date: "2022.11.27",
    media: {
      youtube: "https://youtu.be/ytQhhgHGj_s?si=1CEgihQob3eVA9_G",
    },
  },
  {
    id: "single_メリーゴーランド",
    type: "single",
    title: "メリーゴーランド",
    date: "2022.12.22",
    media: {
      youtube: "https://youtu.be/eWeSqrRk-gs?si=hRmIFkRcRHPvDpOa",
    },
  },
  {
    id: "single_ビリミリオン",
    type: "single",
    title: "ビリミリオン",
    date: "2023.1.19",
    media: {
      youtube: "https://youtu.be/vUsikBoa8i0?si=HILFWiJTNyMvlJV-",
    },
  },
  {
    id: "single_恋人じゃなくなった日",
    type: "single",
    title: "恋人じゃなくなった日",
    date: "2023.2.14",
    media: {
      youtube: "https://youtu.be/ysqGvafOcaQ?si=tqn1DQs7fpMXP-xe",
    },
  },
  {
    id: "single_カーテンコール",
    type: "single",
    title: "カーテンコール",
    date: "2024.7.19",
    media: {
      youtube: "https://youtu.be/9E_gqQ7V5P0?si=9_2t7H-rdZaHoO8T",
    },
  },
  {
    id: "single_DiNA",
    type: "single",
    title: "DiNA",
    date: "2025.1.10",
    media: {
      youtube:
        "https://music.youtube.com/watch?v=UKwwPJEYbgI&si=r4lAGO79Gftykqym",
    },
  },
  {
    id: "single_最&強",
    type: "single",
    title: "最&強",
    date: "2025.4.20",
    media: {
      youtube:
        "https://music.youtube.com/watch?v=wJEvyGMIqhI&si=vXjHiG89MQh3raVM",
    },
  },
  {
    id: "album_壱",
    type: "album",
    title: "壱",
    date: "2022.1.12",
    connections: [
      "collab_『レオ』 acoustic ver. 優里×Tani Yuuki",
      "cover_NEWギターで【ピーターパン】を弾き語りしてみた【YAMAHA】",
      "cover_『かごめ』piano ver.",
      "cover_『ベテルギウス』acoustic ver.",
      "cover_『夏音』 acoustic ver.",
      "cover_『花鳥風月』 acoustic ver.",
      "cover_【新曲】『ミザリー』acoustic ver.",
      "cover_【新曲】『ミズキリ』piano ver.",
      "cover_【新曲】『レオ』piano ver.",
      "cover_【祝！2000万再生】感謝の気持ちを込めて歌います『かくれんぼ』",
      "cover_本人が【かくれんぼ】【ドライフラワー】1人マッシュアップしてみた！",
      "live_YUURI『Betelgeuse』/ ROCK IN JAPAN FESTIVAL 2022",
      "live_Yuuri – BETELGEUSE / THE FIRST TAKE",
      "live_Yuuri – Dry Flower / THE FIRST TAKE",
      "live_Yuuri – Leo / THE FIRST TAKE",
      "live_Yuuri – Shutter / THE FIRST TAKE",
      "live_優里 - かくれんぼ / THE HOME TAKE",
      "track_かくれんぼ",
      "track_かごめ",
      "track_インフィニティ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_ミズキリ",
      "track_レオ",
      "track_夏音",
      "track_桜晴",
      "track_背中",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube:
        "https://music.youtube.com/playlist?list=OLAK5uy_mlwD7dO2vyRTJSah23pCLBdhuLOhfMtb8&si=_Ry6mdIwGHb34mbv",
    },
  },
  {
    id: "track_ベテルギウス",
    type: "track",
    title: "ベテルギウス",
    date: "2021.11.4",
    connections: [
      "cover_『ベテルギウス』acoustic ver.",
      "live_YUURI『Betelgeuse』/ ROCK IN JAPAN FESTIVAL 2022",
      "live_Yuuri – BETELGEUSE / THE FIRST TAKE",
      "track_かくれんぼ",
      "track_かごめ",
      "track_インフィニティ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ミザリー",
      "track_ミズキリ",
      "track_レオ",
      "track_夏音",
      "track_桜晴",
      "track_背中",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube: "https://youtu.be/cbqvxDTLMps?si=zJoRW36-8yLqcS_W",
    },
  },
  {
    id: "track_ドライフラワー",
    type: "track",
    title: "ドライフラワー",
    date: "2020.10.25",
    connections: [
      "cover_本人が【かくれんぼ】【ドライフラワー】1人マッシュアップしてみた！",
      "live_Yuuri – Dry Flower / THE FIRST TAKE",
      "track_かくれんぼ",
      "track_かごめ",
      "track_インフィニティ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_ミズキリ",
      "track_レオ",
      "track_夏音",
      "track_桜晴",
      "track_背中",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube: "https://youtu.be/kzZ6KXDM1RI?si=aVIqMhmXWFGL5f5b",
    },
  },
  {
    id: "track_花鳥風月",
    type: "track",
    title: "花鳥風月",
    date: "2022.1.12",
    connections: [
      "cover_『花鳥風月』 acoustic ver.",
      "track_かくれんぼ",
      "track_かごめ",
      "track_インフィニティ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_ミズキリ",
      "track_レオ",
      "track_夏音",
      "track_桜晴",
      "track_背中",
      "track_飛行船",
    ],
    media: {
      youtube:
        "https://music.youtube.com/watch?v=EzrnNCINmaY&si=WsB0Iu27WWkAIVfe",
    },
  },
  {
    id: "track_ミズキリ",
    type: "track",
    title: "ミズキリ",
    date: "2022.1.12",
    connections: [
      "cover_【新曲】『ミズキリ』piano ver.",
      "track_かくれんぼ",
      "track_かごめ",
      "track_インフィニティ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_レオ",
      "track_夏音",
      "track_桜晴",
      "track_背中",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube:
        "https://music.youtube.com/watch?v=zK2MNC78wE4&si=Z-tdf6Ks6R_Yixh0",
    },
  },
  {
    id: "track_シャッター",
    type: "track",
    title: "シャッター",
    date: "2021.7.7",
    connections: [
      "live_Yuuri – Shutter / THE FIRST TAKE",
      "track_かくれんぼ",
      "track_かごめ",
      "track_インフィニティ",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_ミズキリ",
      "track_レオ",
      "track_夏音",
      "track_桜晴",
      "track_背中",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube: "https://youtu.be/EZ5RGA2UULE?si=kVvjRb5-OutME4Ml",
    },
  },
  {
    id: "track_ミザリー",
    type: "track",
    title: "ミザリー",
    date: "2022.1.12",
    connections: [
      "cover_【新曲】『ミザリー』acoustic ver.",
      "track_かくれんぼ",
      "track_かごめ",
      "track_インフィニティ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミズキリ",
      "track_レオ",
      "track_夏音",
      "track_桜晴",
      "track_背中",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube:
        "https://music.youtube.com/watch?v=nNXB_QO3zA8&si=Pk8yOMu1cxivEcgh",
    },
  },
  {
    id: "track_レオ",
    type: "track",
    title: "レオ",
    date: "2022.1.12",
    connections: [
      "collab_『レオ』 acoustic ver. 優里×Tani Yuuki",
      "cover_【新曲】『レオ』piano ver.",
      "live_Yuuri – Leo / THE FIRST TAKE",
      "track_かくれんぼ",
      "track_かごめ",
      "track_インフィニティ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_ミズキリ",
      "track_夏音",
      "track_桜晴",
      "track_背中",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube: "https://youtu.be/uxYLXaXtH9I?si=9jyRKu8T1rZv5i3X",
    },
  },
  {
    id: "track_ピーターパン",
    type: "track",
    title: "ピーターパン",
    date: "2020.8.9",
    connections: [
      "cover_NEWギターで【ピーターパン】を弾き語りしてみた【YAMAHA】",
      "track_かくれんぼ",
      "track_かごめ",
      "track_インフィニティ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_ミズキリ",
      "track_レオ",
      "track_夏音",
      "track_桜晴",
      "track_背中",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube: "https://youtu.be/9qfPF4fpiHE?si=t4FnaT97_gDdXKYU",
    },
  },
  {
    id: "track_スマホウォーズ",
    type: "track",
    title: "スマホウォーズ",
    date: "2022.1.12",
    connections: [
      "track_かくれんぼ",
      "track_かごめ",
      "track_インフィニティ",
      "track_シャッター",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_ミズキリ",
      "track_レオ",
      "track_夏音",
      "track_桜晴",
      "track_背中",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube:
        "https://music.youtube.com/watch?v=vS65Sw4rmGM&si=Qn62sOaNpoPEArfC",
    },
  },
  {
    id: "track_夏音",
    type: "track",
    title: "夏音",
    date: "2021.9.19",
    connections: [
      "cover_『夏音』 acoustic ver.",
      "track_かくれんぼ",
      "track_かごめ",
      "track_インフィニティ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_ミズキリ",
      "track_レオ",
      "track_桜晴",
      "track_背中",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube:
        "https://music.youtube.com/watch?v=FVGRHm_NWu0&si=i7MG_IKIB0uM3Kwc",
    },
  },
  {
    id: "track_背中",
    type: "track",
    title: "背中",
    date: "2022.1.12",
    connections: [
      "track_かくれんぼ",
      "track_かごめ",
      "track_インフィニティ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_ミズキリ",
      "track_レオ",
      "track_夏音",
      "track_桜晴",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube:
        "https://music.youtube.com/watch?v=GfYQKNH_iuA&si=Q6RiTZagwjEpDz-y",
    },
  },
  {
    id: "track_かごめ",
    type: "track",
    title: "かごめ",
    date: "2020.2.28",
    connections: [
      "cover_『かごめ』piano ver.",
      "track_かくれんぼ",
      "track_インフィニティ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_ミズキリ",
      "track_レオ",
      "track_夏音",
      "track_桜晴",
      "track_背中",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube: "https://youtu.be/PR52T_fpWO4?si=0CUKIYJCw1PcKc3R",
    },
  },
  {
    id: "track_桜晴",
    type: "track",
    title: "桜晴",
    date: "2021.2.19",
    connections: [
      "track_かくれんぼ",
      "track_かごめ",
      "track_インフィニティ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_ミズキリ",
      "track_レオ",
      "track_夏音",
      "track_背中",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube:
        "https://music.youtube.com/watch?v=EYcMOogE_xA&si=ND5oYfCzpCu_p-2S",
    },
  },
  {
    id: "track_インフィニティ",
    type: "track",
    title: "インフィニティ",
    date: "2021.1.23",
    connections: [
      "track_かくれんぼ",
      "track_かごめ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_ミズキリ",
      "track_レオ",
      "track_夏音",
      "track_桜晴",
      "track_背中",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube:
        "https://music.youtube.com/watch?v=qWfnM-8yyBc&si=XtRY7CvD6_ACL0Qa",
    },
  },
  {
    id: "track_飛行船",
    type: "track",
    title: "飛行船",
    date: "2021.4.17",
    connections: [
      "track_かくれんぼ",
      "track_かごめ",
      "track_インフィニティ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_ミズキリ",
      "track_レオ",
      "track_夏音",
      "track_桜晴",
      "track_背中",
      "track_花鳥風月",
    ],
    media: {
      youtube: "https://youtu.be/38xNKy9e-0A?si=omo4dlwKloISMXTw",
    },
  },
  {
    id: "track_かくれんぼ",
    type: "track",
    title: "かくれんぼ",
    date: "2019.12.1",
    connections: [
      "cover_【祝！2000万再生】感謝の気持ちを込めて歌います『かくれんぼ』",
      "live_優里 - かくれんぼ / THE HOME TAKE",
      "track_かごめ",
      "track_インフィニティ",
      "track_シャッター",
      "track_スマホウォーズ",
      "track_ドライフラワー",
      "track_ピーターパン",
      "track_ベテルギウス",
      "track_ミザリー",
      "track_ミズキリ",
      "track_レオ",
      "track_夏音",
      "track_桜晴",
      "track_背中",
      "track_花鳥風月",
      "track_飛行船",
    ],
    media: {
      youtube: "https://youtu.be/7W-6qJnza5w?si=5tjiEsXR9evEaGsT",
    },
  },
  {
    id: "album_弐",
    type: "album",
    title: "弐",
    date: "2023.3.29",
    connections: [
      "collab_『メリーゴーランド』 acoustic ver. 優里×春茶",
      "cover_【最新曲】『うぉ』acoustic ver.",
      "cover_【最新曲】『アストロノーツ』 acoustic ver.",
      "cover_【最新曲】『アダムとイブ』 acoustic ver.",
      "cover_【最新曲】『ガリレオは恋をする』 acoustic ver.",
      "cover_【最新曲】『クリスマスイブ』- 優里 acoustic ver.",
      "cover_【最新曲】『ビリミリオン』 acoustic ver.",
      "live_Yuuri - Billimillion / THE FIRST TAKE",
      "track_うぉ",
      "track_おにごっこ",
      "track_アストロノーツ",
      "track_アダムとイブ",
      "track_ガリレオは恋をする",
      "track_クリスマスイブ",
      "track_タイムマシン ",
      "track_ヒーローの居ない街",
      "track_ビリミリオン",
      "track_フロントライン",
      "track_メリーゴーランド",
      "track_ライラ",
      "track_告白直前酸欠状態",
      "track_恋人じゃなくなった日",
    ],
    media: {
      youtube:
        "https://youtube.com/playlist?list=PLE6sX6v8zDnxRhB4nkyP1VzXrLt104UjN&si=JF-OelfTOW62mkZw",
    },
  },
  {
    id: "track_ビリミリオン",
    type: "track",
    title: "ビリミリオン",
    date: "2023.1.19",
    connections: [
      "cover_【最新曲】『ビリミリオン』 acoustic ver.",
      "live_Yuuri - Billimillion / THE FIRST TAKE",
      "track_うぉ",
      "track_おにごっこ",
      "track_アストロノーツ",
      "track_アダムとイブ",
      "track_ガリレオは恋をする",
      "track_クリスマスイブ",
      "track_タイムマシン ",
      "track_ヒーローの居ない街",
      "track_フロントライン",
      "track_メリーゴーランド",
      "track_ライラ",
      "track_告白直前酸欠状態",
      "track_恋人じゃなくなった日",
    ],
    media: {
      youtube: "https://youtu.be/vUsikBoa8i0?si=HILFWiJTNyMvlJV-",
    },
  },
  {
    id: "track_クリスマスイブ",
    type: "track",
    title: "クリスマスイブ",
    date: "2022.11.27",
    connections: [
      "cover_【最新曲】『クリスマスイブ』- 優里 acoustic ver.",
      "track_うぉ",
      "track_おにごっこ",
      "track_アストロノーツ",
      "track_アダムとイブ",
      "track_ガリレオは恋をする",
      "track_タイムマシン ",
      "track_ヒーローの居ない街",
      "track_ビリミリオン",
      "track_フロントライン",
      "track_メリーゴーランド",
      "track_ライラ",
      "track_告白直前酸欠状態",
      "track_恋人じゃなくなった日",
    ],
    media: {
      youtube: "https://youtu.be/ytQhhgHGj_s?si=1CEgihQob3eVA9_G",
    },
  },
  {
    id: "track_恋人じゃなくなった日",
    type: "track",
    title: "恋人じゃなくなった日",
    date: "2023.2.14",
    connections: [
      "track_うぉ",
      "track_おにごっこ",
      "track_アストロノーツ",
      "track_アダムとイブ",
      "track_ガリレオは恋をする",
      "track_クリスマスイブ",
      "track_タイムマシン ",
      "track_ヒーローの居ない街",
      "track_ビリミリオン",
      "track_フロントライン",
      "track_メリーゴーランド",
      "track_ライラ",
      "track_告白直前酸欠状態",
    ],
    media: {
      youtube: "https://youtu.be/ysqGvafOcaQ?si=tqn1DQs7fpMXP-xe",
    },
  },
  {
    id: "track_アストロノーツ",
    type: "track",
    title: "アストロノーツ",
    date: "2023.3.29",
    connections: [
      "cover_【最新曲】『アストロノーツ』 acoustic ver.",
      "track_うぉ",
      "track_おにごっこ",
      "track_アダムとイブ",
      "track_ガリレオは恋をする",
      "track_クリスマスイブ",
      "track_タイムマシン ",
      "track_ヒーローの居ない街",
      "track_ビリミリオン",
      "track_フロントライン",
      "track_メリーゴーランド",
      "track_ライラ",
      "track_告白直前酸欠状態",
      "track_恋人じゃなくなった日",
    ],
    media: {
      youtube: "https://youtu.be/TKN3PDIXcV4?si=2GkNB91LC6JZ-sRx",
    },
  },
  {
    id: "track_アダムとイブ",
    type: "track",
    title: "アダムとイブ",
    date: "2023.3.29",
    connections: [
      "collab_『メリーゴーランド』 acoustic ver. 優里×春茶",
      "cover_【最新曲】『アダムとイブ』 acoustic ver.",
      "track_うぉ",
      "track_おにごっこ",
      "track_アストロノーツ",
      "track_ガリレオは恋をする",
      "track_クリスマスイブ",
      "track_タイムマシン ",
      "track_ヒーローの居ない街",
      "track_ビリミリオン",
      "track_フロントライン",
      "track_メリーゴーランド",
      "track_ライラ",
      "track_告白直前酸欠状態",
      "track_恋人じゃなくなった日",
    ],
    media: {
      youtube: "https://youtu.be/Px5G7BPUDhc?si=fMq-4Dke3VpdpMhD",
    },
  },
  {
    id: "track_ヒーローの居ない街",
    type: "track",
    title: "ヒーローの居ない街",
    date: "2023.3.29",
    connections: [
      "track_うぉ",
      "track_おにごっこ",
      "track_アストロノーツ",
      "track_アダムとイブ",
      "track_ガリレオは恋をする",
      "track_クリスマスイブ",
      "track_タイムマシン ",
      "track_ビリミリオン",
      "track_フロントライン",
      "track_メリーゴーランド",
      "track_ライラ",
      "track_告白直前酸欠状態",
      "track_恋人じゃなくなった日",
    ],
    media: {
      youtube: "https://youtu.be/9Ygmg6WB9RI?si=FpwZ9KnZPorrNbxQ",
    },
  },
  {
    id: "track_ライラ",
    type: "track",
    title: "ライラ",
    date: "2023.3.29",
    connections: [
      "track_うぉ",
      "track_おにごっこ",
      "track_アストロノーツ",
      "track_アダムとイブ",
      "track_ガリレオは恋をする",
      "track_クリスマスイブ",
      "track_タイムマシン ",
      "track_ヒーローの居ない街",
      "track_ビリミリオン",
      "track_フロントライン",
      "track_メリーゴーランド",
      "track_告白直前酸欠状態",
      "track_恋人じゃなくなった日",
    ],
    media: {
      youtube: "https://youtu.be/0BmjEDLs2EY?si=HBYheW24DD5VUr2I",
    },
  },
  {
    id: "track_ガリレオは恋をする",
    type: "track",
    title: "ガリレオは恋をする",
    date: "2023.3.29",
    connections: [
      "cover_【最新曲】『ガリレオは恋をする』 acoustic ver.",
      "track_うぉ",
      "track_おにごっこ",
      "track_アストロノーツ",
      "track_アダムとイブ",
      "track_クリスマスイブ",
      "track_タイムマシン ",
      "track_ヒーローの居ない街",
      "track_ビリミリオン",
      "track_フロントライン",
      "track_メリーゴーランド",
      "track_ライラ",
      "track_告白直前酸欠状態",
      "track_恋人じゃなくなった日",
    ],
    media: {
      youtube: "https://youtu.be/QTC8AE6cKOk?si=xE_HMCm6k5MCm1fm",
    },
  },
  {
    id: "track_おにごっこ",
    type: "track",
    title: "おにごっこ",
    date: "2023.3.29",
    connections: [
      "track_うぉ",
      "track_アストロノーツ",
      "track_アダムとイブ",
      "track_ガリレオは恋をする",
      "track_クリスマスイブ",
      "track_タイムマシン ",
      "track_ヒーローの居ない街",
      "track_ビリミリオン",
      "track_フロントライン",
      "track_メリーゴーランド",
      "track_ライラ",
      "track_告白直前酸欠状態",
      "track_恋人じゃなくなった日",
    ],
    media: {
      youtube: "https://youtu.be/m3VnVRHOMZM?si=yvdRHevBJtZTbXUS",
    },
  },
  {
    id: "track_うぉ",
    type: "track",
    title: "うぉ",
    date: "2022.5.13",
    connections: [
      "cover_【最新曲】『うぉ』acoustic ver.",
      "track_おにごっこ",
      "track_アストロノーツ",
      "track_アダムとイブ",
      "track_ガリレオは恋をする",
      "track_クリスマスイブ",
      "track_タイムマシン ",
      "track_ヒーローの居ない街",
      "track_ビリミリオン",
      "track_フロントライン",
      "track_メリーゴーランド",
      "track_ライラ",
      "track_告白直前酸欠状態",
      "track_恋人じゃなくなった日",
    ],
    media: {
      youtube: "https://youtu.be/-0OZ7yueQzA?si=oVs-purAjS1skODK",
    },
  },
  {
    id: "track_フロントライン",
    type: "track",
    title: "フロントライン",
    date: "2023.3.29",
    connections: [
      "track_うぉ",
      "track_おにごっこ",
      "track_アストロノーツ",
      "track_アダムとイブ",
      "track_ガリレオは恋をする",
      "track_クリスマスイブ",
      "track_タイムマシン ",
      "track_ヒーローの居ない街",
      "track_ビリミリオン",
      "track_メリーゴーランド",
      "track_ライラ",
      "track_告白直前酸欠状態",
      "track_恋人じゃなくなった日",
    ],
    media: {
      youtube: "https://youtu.be/xxEz8bkYshM?si=lqviRdd3YEnf3o7p",
    },
  },
  {
    id: "track_タイムマシン ",
    type: "track",
    title: "タイムマシン ",
    date: "2022.7.12",
    connections: [
      "track_うぉ",
      "track_おにごっこ",
      "track_アストロノーツ",
      "track_アダムとイブ",
      "track_ガリレオは恋をする",
      "track_クリスマスイブ",
      "track_ヒーローの居ない街",
      "track_ビリミリオン",
      "track_フロントライン",
      "track_メリーゴーランド",
      "track_ライラ",
      "track_告白直前酸欠状態",
      "track_恋人じゃなくなった日",
    ],
    media: {
      youtube: "https://youtu.be/LfL6qgagsjU?si=D4L-dzldM1YojZM2",
    },
  },
  {
    id: "track_告白直前酸欠状態",
    type: "track",
    title: "告白直前酸欠状態",
    date: "2023.3.29",
    connections: [
      "track_うぉ",
      "track_おにごっこ",
      "track_アストロノーツ",
      "track_アダムとイブ",
      "track_ガリレオは恋をする",
      "track_クリスマスイブ",
      "track_タイムマシン ",
      "track_ヒーローの居ない街",
      "track_ビリミリオン",
      "track_フロントライン",
      "track_メリーゴーランド",
      "track_ライラ",
      "track_恋人じゃなくなった日",
    ],
    media: {
      youtube: "https://youtu.be/27je_FPhNMY?si=UtExthSFcJz-L0Rd",
    },
  },
  {
    id: "track_メリーゴーランド",
    type: "track",
    title: "メリーゴーランド",
    date: "2022.12.22",
    connections: [
      "track_うぉ",
      "track_おにごっこ",
      "track_アストロノーツ",
      "track_アダムとイブ",
      "track_ガリレオは恋をする",
      "track_クリスマスイブ",
      "track_タイムマシン ",
      "track_ヒーローの居ない街",
      "track_ビリミリオン",
      "track_フロントライン",
      "track_ライラ",
      "track_告白直前酸欠状態",
      "track_恋人じゃなくなった日",
    ],
    media: {
      youtube: "https://youtu.be/eWeSqrRk-gs?si=hRmIFkRcRHPvDpOa",
    },
  },
  {
    id: "album_響",
    type: "album",
    title: "響",
    date: "2023.11.29",
    media: {
      youtube:
        "https://youtube.com/playlist?list=PLS6a_tsrzurTyXj0uxzQZXP2T_RK-KWWt&si=FkiDs-06BylPtrMY",
    },
  },
  {
    id: "track_ビリミリオン -オーケストラアレンジver.",
    type: "track",
    title: "ビリミリオン -オーケストラアレンジver.",
    date: "2023.11.29",
    media: {
      youtube: "https://youtu.be/fyobo5zkqVk?si=lQ9UuZ5LDoAWAkqV",
    },
  },
  {
    id: "track_ベテルギウス -オーケストラアレンジver.",
    type: "track",
    title: "ベテルギウス -オーケストラアレンジver.",
    date: "2023.11.29",
    media: {
      youtube: "https://youtu.be/obdqxPylgyY?si=vuzbvS6JXuSKI_LL",
    },
  },
  {
    id: "track_かくれんぼ -オーケストラアレンジver.",
    type: "track",
    title: "かくれんぼ -オーケストラアレンジver.",
    date: "2023.11.29",
    media: {
      youtube: "https://youtu.be/KDPJ7Y_oBi0?si=SdIxzvcgUbTyUiiL",
    },
  },
  {
    id: "track_ドライフラワー -オーケストラアレンジver.",
    type: "track",
    title: "ドライフラワー -オーケストラアレンジver.",
    date: "2023.11.29",
    media: {
      youtube: "https://youtu.be/oDOzPTpepso?si=_BECZwcI5bJwridi",
    },
  },
  {
    id: "track_アダムとイブ -オーケストラアレンジver.",
    type: "track",
    title: "アダムとイブ -オーケストラアレンジver.",
    date: "2023.11.29",
    media: {
      youtube: "https://youtu.be/EsTzHKXmfmg?si=-l-ZDcMaWog5OUIi",
    },
  },
  {
    id: "track_レオ -オーケストラアレンジver.",
    type: "track",
    title: "レオ -オーケストラアレンジver.",
    date: "2023.11.29",
    media: {
      youtube: "https://youtu.be/dEaE5e37bwo?si=dhbpK96QzEuCVrS0",
    },
  },
  {
    id: "track_アストロノーツ -オーケストラアレンジver.",
    type: "track",
    title: "アストロノーツ -オーケストラアレンジver.",
    date: "2023.11.29",
    media: {
      youtube: "https://youtu.be/P5SLKIfzo6M?si=qOUQvIKB-0c0Qrhg",
    },
  },
  {
    id: "track_ガリレオは恋をする -オーケストラアレンジver.",
    type: "track",
    title: "ガリレオは恋をする -オーケストラアレンジver.",
    date: "2023.11.29",
    media: {
      youtube: "https://youtu.be/Odtcaj0AB0w?si=uymCXRjXCHRR4VvH",
    },
  },
  {
    id: "track_かごめ -オーケストラアレンジver.",
    type: "track",
    title: "かごめ -オーケストラアレンジver.",
    date: "2023.11.29",
    media: {
      youtube: "https://youtu.be/67xffgyqKE0?si=imzc9kTby2R5Ql9D",
    },
  },
  {
    id: "track_ピーターパン -オーケストラアレンジver.",
    type: "track",
    title: "ピーターパン -オーケストラアレンジver.",
    date: "2023.11.29",
    media: {
      youtube: "https://youtu.be/kCHDCH9wv_w?si=GG_HxRzlTan2PTe3",
    },
  },
  {
    id: "track_うぉ -オーケストラアレンジver.",
    type: "track",
    title: "うぉ -オーケストラアレンジver.",
    date: "2023.11.29",
    media: {
      youtube: "https://youtu.be/PtZjZK1cER4?si=eCQrmIZUBnvw897r",
    },
  },
  {
    id: "track_メリーゴーランド -オーケストラアレンジver.",
    type: "track",
    title: "メリーゴーランド -オーケストラアレンジver.",
    date: "2023.11.29",
    media: {
      youtube: "https://youtu.be/aaXG7rPzH_g?si=pvHNOdzY2rkFkap1",
    },
  },
  {
    id: "cover_【祝！2000万再生】感謝の気持ちを込めて歌います『かくれんぼ』",
    type: "cover",
    title: "【祝！2000万再生】感謝の気持ちを込めて歌います『かくれんぼ』",
    date: "2020.11.30",
    connections: ["track_かくれんぼ"],
    media: {
      youtube: "https://youtu.be/9b-7gQLhuvI?si=GjbAsETeAqDgQ2-k",
    },
  },
  {
    id: "cover_本人が【かくれんぼ】【ドライフラワー】1人マッシュアップしてみた！",
    type: "cover",
    title: "本人が【かくれんぼ】【ドライフラワー】1人マッシュアップしてみた！",
    date: "2020.12.31",
    connections: ["track_ドライフラワー"],
    media: {
      youtube: "https://youtu.be/FB_W9GpSSzI?si=AnHAUsjhOigYKIlM",
    },
  },
  {
    id: "cover_NEWギターで【ピーターパン】を弾き語りしてみた【YAMAHA】",
    type: "cover",
    title: "NEWギターで【ピーターパン】を弾き語りしてみた【YAMAHA】",
    date: "2021.1.16",
    connections: ["track_ピーターパン"],
    media: {
      youtube: "https://youtu.be/ykeBpaGk14c?si=lJblrBX0_4pZXK11",
    },
  },
  {
    id: "cover_【新曲】『レオ』piano ver.",
    type: "cover",
    title: "【新曲】『レオ』piano ver.",
    date: "2022.1.10",
    connections: ["track_レオ"],
    media: {
      youtube: "https://youtu.be/iYXt3NU1Vao?si=RuSNcZ2A_JAABnoP",
    },
  },
  {
    id: "cover_【新曲】『ミズキリ』piano ver.",
    type: "cover",
    title: "【新曲】『ミズキリ』piano ver.",
    date: "2022.1.14",
    connections: ["track_ミズキリ"],
    media: {
      youtube: "https://youtu.be/XdquKj6ucEI?si=blp0JlTDqTLShy9w",
    },
  },
  {
    id: "cover_『かごめ』piano ver.",
    type: "cover",
    title: "『かごめ』piano ver.",
    date: "2022.2.10",
    connections: ["track_かごめ"],
    media: {
      youtube: "https://youtu.be/za6Ly8cb_J8?si=RGD6lNQOWVPCZbVc",
    },
  },
  {
    id: "cover_『花鳥風月』 acoustic ver.",
    type: "cover",
    title: "『花鳥風月』 acoustic ver.",
    date: "2022.2.18",
    connections: ["track_花鳥風月"],
    media: {
      youtube: "https://youtu.be/iakwCmS56rA?si=P9Ysf1gZnSgNCUPz",
    },
  },
  {
    id: "cover_【新曲】『ミザリー』acoustic ver.",
    type: "cover",
    title: "【新曲】『ミザリー』acoustic ver.",
    date: "2022.2.25",
    connections: ["track_ミザリー"],
    media: {
      youtube: "https://youtu.be/7TYXR0rbzsk?si=jv75DTI6SD_eIoRC",
    },
  },
  {
    id: "collab_『パラレルワールド』 acoustic ver. 優里×川崎鷹也",
    type: "collab",
    title: "『パラレルワールド』 acoustic ver. 優里×川崎鷹也",
    date: "2022.4.12",
    media: {
      youtube: "https://youtu.be/oE-BhCvGKe8?si=jQ8e9MJp5_zP9is4",
    },
  },
  {
    id: "cover_【新曲】『ノンタイトル』acoustic ver.",
    type: "cover",
    title: "【新曲】『ノンタイトル』acoustic ver.",
    date: "2022.4.19",
    media: {
      youtube: "https://youtu.be/yPJyoCzRd4A?si=0Qj6XA20elHZdz8O",
    },
  },
  {
    id: "collab_『君の為のキミノウタ』 acoustic ver. 優里×川崎鷹也",
    type: "collab",
    title: "『君の為のキミノウタ』 acoustic ver. 優里×川崎鷹也",
    date: "2022.4.26",
    media: {
      youtube: "https://youtu.be/N8av8Cam8do?si=C2Sez92e9ZqgiV5q",
    },
  },
  {
    id: "cover_【新曲】『タイムマシン』acoustic ver.",
    type: "cover",
    title: "【新曲】『タイムマシン』acoustic ver.",
    date: "2022.5.6",
    media: {
      youtube: "https://youtu.be/55DZyxBijLE?si=1sxjH5JBM278WLjc",
    },
  },
  {
    id: "cover_【最新曲】『うぉ』acoustic ver.",
    type: "cover",
    title: "【最新曲】『うぉ』acoustic ver.",
    date: "2022.5.12",
    connections: ["track_うぉ"],
    media: {
      youtube: "https://youtu.be/3OTQx5LH0J8?si=o8rYAyDzrJM9wDRL",
    },
  },
  {
    id: "cover_『ベテルギウス』acoustic ver.",
    type: "cover",
    title: "『ベテルギウス』acoustic ver.",
    date: "2022.5.27",
    connections: ["track_ベテルギウス"],
    media: {
      youtube: "https://youtu.be/LhdQJTbHhrk?si=ZlONUxMJ4SQYpdnX",
    },
  },
  {
    id: "collab_『FIRE』 acoustic ver. 優里×朝倉未来",
    type: "collab",
    title: "『FIRE』 acoustic ver. 優里×朝倉未来",
    date: "2022.6.11",
    media: {
      youtube: "https://youtu.be/aJlNS-JvO9E?si=72m_HRLaW7Mofblm",
    },
  },
  {
    id: "collab_『ロングヘアー』 acoustic ver. 優里×NARI",
    type: "collab",
    title: "『ロングヘアー』 acoustic ver. 優里×NARI",
    date: "2022.6.17",
    media: {
      youtube: "https://youtu.be/P0R3axUIGaI?si=MKalouff-lmzmgSw",
    },
  },
  {
    id: "collab_『W/X/Y』 acoustic ver. 優里×Tani Yuuki",
    type: "collab",
    title: "『W/X/Y』 acoustic ver. 優里×Tani Yuuki",
    date: "2022.07..09",
    media: {
      youtube: "https://youtu.be/ugbUFR7lzkk?si=bb_22xl1uxlV4OuJ",
    },
  },
  {
    id: "collab_『レオ』 acoustic ver. 優里×Tani Yuuki",
    type: "collab",
    title: "『レオ』 acoustic ver. 優里×Tani Yuuki",
    date: "2022.7.14",
    connections: ["track_レオ"],
    media: {
      youtube: "https://youtu.be/-s8pCoWqkPU?si=3jAOJU2J9Q7dmIDv",
    },
  },
  {
    id: "collab_『＝ (イコール)』 acoustic ver. 優里×るな（ばんばんざい）",
    type: "collab",
    title: "『＝ (イコール)』 acoustic ver. 優里×るな（ばんばんざい）",
    date: "2022.7.20",
    media: {
      youtube: "https://youtu.be/RcBb-W02DBQ?si=7FnYaspjC9JEoU-q",
    },
  },
  {
    id: "collab_『好きだよ』 acoustic ver. 優里×まるり",
    type: "collab",
    title: "『好きだよ』 acoustic ver. 優里×まるり",
    date: "2022.8.20",
    media: {
      youtube: "https://youtu.be/i2idmD29DrU?si=nVW4Fwgz2IT36qm6",
    },
  },
  {
    id: "cover_『夏音』 acoustic ver.",
    type: "cover",
    title: "『夏音』 acoustic ver.",
    date: "2022.8.30",
    connections: ["track_夏音"],
    media: {
      youtube: "https://youtu.be/0oLzTI3pgK8?si=fkwZxx9N14aE7UDb",
    },
  },
  {
    id: "collab_『宵花火』 acoustic ver. 優里×ばんばんざ",
    type: "collab",
    title: "『宵花火』 acoustic ver. 優里×ばんばんざ",
    date: "2022.9.20",
    media: {
      youtube: "https://youtu.be/XwCa2CbSmmo?si=H-4DY_lltSe20JdJ",
    },
  },
  {
    id: "collab_『ねぇ』 acoustic ver. 優里×YOAKE",
    type: "collab",
    title: "『ねぇ』 acoustic ver. 優里×YOAKE",
    date: "2022.9.24",
    media: {
      youtube: "https://youtu.be/OBF5TYnkHQA?si=Iv-3mK8g4afnRqw7",
    },
  },
  {
    id: "collab_『愛sing』 acoustic ver. 優里×るな（ばんばんざい）",
    type: "collab",
    title: "『愛sing』 acoustic ver. 優里×るな（ばんばんざい）",
    date: "2022.11.19",
    media: {
      youtube: "https://youtu.be/DF8mhiJ2mc4?si=geH-N13sKQO8BbhM",
    },
  },
  {
    id: "cover_【最新曲】『クリスマスイブ』- 優里 acoustic ver.",
    type: "cover",
    title: "【最新曲】『クリスマスイブ』- 優里 acoustic ver.",
    date: "2022.11.26",
    connections: ["track_クリスマスイブ"],
    media: {
      youtube: "https://youtu.be/YY-5hOhbLzg?si=6gGqHHFb0bGa5yfo",
    },
  },
  {
    id: "cover_【最新曲】『ビリミリオン』 acoustic ver.",
    type: "cover",
    title: "【最新曲】『ビリミリオン』 acoustic ver.",
    date: "2023.2.23",
    connections: ["track_ビリミリオン"],
    media: {
      youtube: "https://youtu.be/y9adEzBqAJI?si=8SJ7pTP8oziDB4LE",
    },
  },
  {
    id: "collab_『幸せについて、僕が考えたこと』 acoustic ver. 優里×井上絃",
    type: "collab",
    title: "『幸せについて、僕が考えたこと』 acoustic ver. 優里×井上絃",
    date: "2023.3.10",
    media: {
      youtube: "https://youtu.be/j10vF0x0k_A?si=B3uO_M9C4mbGYR7v",
    },
  },
  {
    id: "cover_【最新曲】『アダムとイブ』 acoustic ver.",
    type: "cover",
    title: "【最新曲】『アダムとイブ』 acoustic ver.",
    date: "2023.3.23",
    connections: ["track_アダムとイブ"],
    media: {
      youtube: "https://youtu.be/Px5G7BPUDhc?si=RYALPME7nnxuvcKC",
    },
  },
  {
    id: "collab_『メリーゴーランド』 acoustic ver. 優里×春茶",
    type: "collab",
    title: "『メリーゴーランド』 acoustic ver. 優里×春茶",
    date: "2023.3.27",
    connections: ["track_アダムとイブ"],
    media: {
      youtube: "https://youtu.be/Px5G7BPUDhc?si=lXaDEek92bB8mviZ",
    },
  },
  {
    id: "cover_【最新曲】『ガリレオは恋をする』 acoustic ver.",
    type: "cover",
    title: "【最新曲】『ガリレオは恋をする』 acoustic ver.",
    date: "2023.3.29",
    connections: ["track_ガリレオは恋をする"],
    media: {
      youtube: "https://youtu.be/QTC8AE6cKOk?si=t88Z3FZ4ZzJIzFcz",
    },
  },
  {
    id: "cover_【最新曲】『アストロノーツ』 acoustic ver.",
    type: "cover",
    title: "【最新曲】『アストロノーツ』 acoustic ver.",
    date: "2023.5.6",
    connections: ["track_アストロノーツ"],
    media: {
      youtube: "https://youtu.be/rE-fvTaSKBQ?si=UjPCaMf-qnB8ipXf",
    },
  },
  {
    id: "collab_『晩餐歌』 acoustic ver. tuki.×優里",
    type: "collab",
    title: "『晩餐歌』 acoustic ver. tuki.×優里",
    date: "2023.11.6",
    media: {
      youtube: "https://youtu.be/r93rVW--5ZU?si=6ArOOyhKmFGCnLxz",
    },
  },
  {
    id: "collab_『サクラキミワタシ』 acoustic ver. 優里×tuki.",
    type: "collab",
    title: "『サクラキミワタシ』 acoustic ver. 優里×tuki.",
    date: "2024.3.1",
    media: {
      youtube: "https://youtu.be/Lp6OiPCDYYw?si=1JnLqVCojgzmOHNy",
    },
  },
  {
    id: "live_Yuuri – Leo / THE FIRST TAKE",
    type: "live",
    title: "Yuuri – Leo / THE FIRST TAKE",
    date: "2022.8.19",
    connections: ["track_レオ"],
    media: {
      youtube: "https://youtu.be/cpuT1AWuRx8?si=tnzF_OIP6pk3K-DP",
    },
  },
  {
    id: "live_Yuuri – Dry Flower / THE FIRST TAKE",
    type: "live",
    title: "Yuuri – Dry Flower / THE FIRST TAKE",
    date: "2020.10.30",
    connections: ["track_ドライフラワー"],
    media: {
      youtube: "https://youtu.be/yXZd7xVdpJ0?si=fqenGsH3DlxjAFk-",
    },
  },
  {
    id: "live_Yuuri – BETELGEUSE / THE FIRST TAKE",
    type: "live",
    title: "Yuuri – BETELGEUSE / THE FIRST TAKE",
    date: "2021.10.13",
    connections: ["track_ベテルギウス"],
    media: {
      youtube: "https://youtu.be/-n790YakYKc?si=sMahKHbXwbwUTbth",
    },
  },
  {
    id: "live_Yuuri – Shutter / THE FIRST TAKE",
    type: "live",
    title: "Yuuri – Shutter / THE FIRST TAKE",
    date: "2021.10.1",
    connections: ["track_シャッター"],
    media: {
      youtube: "https://youtu.be/s984zMNLL2o?si=z_SjZfD2IjVdP54D",
    },
  },
  {
    id: "live_優里 - かくれんぼ / THE HOME TAKE",
    type: "live",
    title: "優里 - かくれんぼ / THE HOME TAKE",
    date: "2020.7.10",
    connections: ["track_かくれんぼ"],
    media: {
      youtube: "https://youtu.be/cv3dWFr4HSc?si=_DR-DRPGwgwvbqSc",
    },
  },
  {
    id: "live_Yuuri - Billimillion / THE FIRST TAKE",
    type: "live",
    title: "Yuuri - Billimillion / THE FIRST TAKE",
    date: "2024.12.20",
    connections: ["track_ビリミリオン"],
    media: {
      youtube: "https://youtu.be/_VfNDvHwhG4?si=ejHJ984ttBS3fFuv",
    },
  },
  {
    id: "live_YUURI『Betelgeuse』/ ROCK IN JAPAN FESTIVAL 2022",
    type: "live",
    title: "YUURI『Betelgeuse』/ ROCK IN JAPAN FESTIVAL 2022",
    date: "2022.12.21",
    connections: ["track_ベテルギウス"],
    media: {
      youtube: "https://youtu.be/dcuNCqRhoUI?si=vGhO3rxZ5fH2KvaP",
    },
  },
];
